name: Build_And_UnitTest

on:
  push:
    branches: [ dev, main, 'feat/**' ]
  pull_request:
    branches: [ dev, main ]

jobs:

  linux:    
    name: build on ubuntu-latest
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x 
  
    - name: Build with dotnet      
      run: |
        dotnet build CoverallsDemo.sln

    - name: Run tests
      run: |
        dotnet test MyTestProject/MyTestProject.csproj --collect:"XPlat Code Coverage"

    - name: ReportGenerator
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool

        reportgenerator -reports:"${{ github.workspace }}/MyTestProject/TestResults/**/coverage.cobertura.xml" \
            -targetdir:"${{ github.workspace }}/coverage" \
            -reporttypes:lcov
        
        cp ${{ github.workspace }}/MyTestProject/TestResults/*/coverage.cobertura.xml  ${{ github.workspace }}/coverage   

        ls ${{ github.workspace }}/coverage    
      
    # - name: Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     path-to-lcov:  ${{ github.workspace }}/coverage/lcov.info
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: ${{ github.workspace }}/coverage/coverage.cobertura.xml       
        name: codecov-umbrella
        verbose: true

    